const users = [
  {
    name: 'Arjun Reddy',
    email: 'arjun@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022001',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 7.8,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['python.basics', 'javascript.basics', 'react.basics', 'sql.basics'],
    },
  },
  {
    name: 'Prof. Lakshmi Naidu',
    email: 'lakshmi.naidu@mrdu.edu',
    password: 'faculty123',
    role: 'faculty',
    onboarded: true,
    faculty: {
      department: 'CSE',
      designation: 'Associate Professor',
      employeeId: 'FAC2019012',
      specializations: ['Python Programming', 'Data Structures', 'Object-Oriented Programming'],
    },
  },
  {
    name: 'Dr. Srinivas Rao',
    email: 'admin@mrdu.edu',
    password: 'admin123',
    role: 'admin',
    onboarded: true,
  },
  {
    name: 'Ravi Menon',
    email: 'ravi@techspark.com',
    password: 'recruiter123',
    role: 'recruiter',
    onboarded: true,
    recruiter: {
      company: 'TechSpark Solutions',
      designation: 'Senior Technical Recruiter',
      verified: true,
    },
  },
  {
    name: 'Priya Sharma',
    email: 'priya.sharma@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022002',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 8.5,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['python.basics', 'python.oop.classes', 'react.basics', 'react.hooks', 'mongodb.basics'],
    },
  },
  {
    name: 'Rohit Verma',
    email: 'rohit.verma@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022003',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 5.2,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['c.basics', 'html.basics'],
    },
  },
  {
    name: 'Sneha Patil',
    email: 'sneha.patil@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'IT2022001',
      branch: 'IT',
      year: 3,
      semester: 5,
      cgpa: 9.1,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['python.basics', 'python.oop.classes', 'ml.supervised', 'data.eda', 'python.pandas'],
    },
  },
  {
    name: 'Vikram Singh',
    email: 'vikram.singh@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022004',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 6.0,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['java.basics', 'sql.basics'],
    },
  },
  {
    name: 'Ananya Desai',
    email: 'ananya.desai@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'AIML2022001',
      branch: 'AIML',
      year: 3,
      semester: 5,
      cgpa: 8.9,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['python.basics', 'ml.supervised', 'ml.unsupervised', 'dl.neural_networks', 'python.tensorflow'],
    },
  },
  {
    name: 'Karthik Nair',
    email: 'karthik.nair@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022005',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 4.5,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['c.basics'],
    },
  },
  {
    name: 'Meera Joshi',
    email: 'meera.joshi@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'IT2022002',
      branch: 'IT',
      year: 3,
      semester: 5,
      cgpa: 7.2,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['html.basics', 'css.basics', 'javascript.basics', 'react.basics'],
    },
  },
  {
    name: 'Aditya Kulkarni',
    email: 'aditya.kulkarni@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'ECE2022001',
      branch: 'ECE',
      year: 3,
      semester: 5,
      cgpa: 6.8,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['python.basics', 'c.basics', 'domain.cn'],
    },
  },
  {
    name: 'Divya Lakshmi',
    email: 'divya.lakshmi@mrdu.edu',
    password: 'test123',
    role: 'student',
    onboarded: true,
    student: {
      rollNo: 'CSE2022006',
      branch: 'CSE',
      year: 3,
      semester: 5,
      cgpa: 8.2,
      admissionDate: new Date('2022-08-01'),
      placementStatus: 'not_placed',
      selfDeclaredSkills: ['javascript.basics', 'javascript.es6', 'node.express', 'rest.api', 'mongodb.basics', 'react.hooks'],
    },
  },
];

export default users;
