"use client";

import { useEffect, useState } from 'react';
import NeuCard from '@/components/shared/NeuCard';
import NeuButton from '@/components/shared/NeuButton';
import { NeuRadarChart } from '@/components/shared/NeuChart';
import NeuBadge from '@/components/shared/NeuBadge';
import { DashboardSkeleton } from '@/components/shared/LoadingSpinner';
import PageTransition, { StaggerItem } from '@/components/shared/PageTransition';
import { FiCheckSquare, FiSquare, FiTarget, FiCompass, FiBookOpen, FiCpu, FiCheckCircle, FiLayers } from 'react-icons/fi';
import api from '@/lib/api';

export default function CareerPathTrackerPage() {
  const [roles, setRoles] = useState([]);
  const [selectedRole, setSelectedRole] = useState('fullstack-developer');
  const [knownSkillsInput, setKnownSkillsInput] = useState('React, JavaScript, HTML/CSS, Git');
  const [learningGoalsInput, setLearningGoalsInput] = useState('System Design, Docker, Microservices, MongoDB');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generatingPlan, setGeneratingPlan] = useState(false);

  // Active Milestones List
  const [activeMilestones, setActiveMilestones] = useState([
    {
      week: 1,
      title: 'Week 1: Core Fundamentals & Data Structures',
      description: 'Master Array operations, HashMaps, Recursion, and Binary Search Trees.',
      completed: false,
      goals: [
        { id: 'w1-g1', label: 'Master Array operations and Time Complexity analysis', done: true },
        { id: 'w1-g2', label: 'Implement HashMaps and collision resolution strategies', done: true },
        { id: 'w1-g3', label: 'Practice Binary Search Trees & Tree Traversal algorithms', done: false },
        { id: 'w1-g4', label: 'Complete 5 practice MCQs on recursion', done: false },
      ]
    },
    {
      week: 2,
      title: 'Week 2: Fullstack Architecture & REST APIs',
      description: 'Build Node.js Express services, MongoDB schemas, and React State Management.',
      completed: false,
      goals: [
        { id: 'w2-g1', label: 'Design Mongoose schema for User and Assessment models', done: false },
        { id: 'w2-g2', label: 'Build JWT Authentication middleware and protected routes', done: false },
        { id: 'w2-g3', label: 'Create React custom hooks for async API fetching', done: false },
      ]
    },
    {
      week: 3,
      title: 'Week 3: System Design & Production Deployment',
      description: 'Implement Microservices, Redis Caching, and Docker deployment pipelines.',
      completed: false,
      goals: [
        { id: 'w3-g1', label: 'Implement Redis caching for high-frequency database queries', done: false },
        { id: 'w3-g2', label: 'Write Dockerfile and docker-compose configurations', done: false },
      ]
    }
  ]);

  useEffect(() => {
    api.get('/student/readiness').then(res => {
      if (res.data.roles) {
        setRoles(res.data.roles);
        if (res.data.roles.length > 0 && !selectedRole) {
          setSelectedRole(res.data.roles[0].roleId);
        }
      }
    }).catch(console.error);
  }, []);

  useEffect(() => {
    if (!selectedRole) return;
    setLoading(true);
    api.get(`/student/readiness?targetRole=${selectedRole}`)
      .then(res => {
        setData(res.data);
        setLoading(false);
      })
      .catch((e) => {
        console.error(e);
        setLoading(false);
      });
  }, [selectedRole]);

  const handleGenerateAiStudyPlan = async () => {
    setGeneratingPlan(true);
    try {
      const res = await api.post('/student/study-plan/generate', {
        targetRole: selectedRole,
        knownSkills: knownSkillsInput.split(',').map(s => s.trim()).filter(Boolean),
        learningGoals: learningGoalsInput.split(',').map(s => s.trim()).filter(Boolean),
      });

      const generatedWeeks = res.data.plan?.weeks || [];
      if (generatedWeeks.length > 0) {
        const mappedMilestones = generatedWeeks.map((w, i) => ({
          week: w.weekNumber || i + 1,
          title: `Week ${w.weekNumber}: ${w.focusSkills?.join(', ') || 'Core Competencies'}`,
          description: w.milestone || 'Personalized AI study milestone.',
          completed: false,
          goals: (w.activities || []).map((act, idx) => ({
            id: `gen-w${w.weekNumber}-g${idx}`,
            label: `${act.title} (${act.hours || 2} hrs)`,
            done: false,
          }))
        }));
        setActiveMilestones(mappedMilestones);
        alert('Personalized 4-Week AI Study Plan Generated by Agent 13!');
      }
    } catch (e) {
      alert('Plan Generation failed: ' + (e.response?.data?.error || e.message));
    }
    setGeneratingPlan(false);
  };

  const handleToggleGoal = async (milestoneIndex, goalId) => {
    const updated = [...activeMilestones];
    const milestone = updated[milestoneIndex];
    const goal = milestone.goals.find(g => g.id === goalId);
    if (goal) {
      goal.done = !goal.done;
      milestone.completed = milestone.goals.every(g => g.done);
      setActiveMilestones(updated);

      try {
        await api.post('/student/milestones/toggle', {
          targetRole: selectedRole,
          goalId,
          done: goal.done,
        });
      } catch (err) {
        console.error('Failed to sync milestone goal:', err);
      }
    }
  };

  const totalGoals = activeMilestones.flatMap(m => m.goals).length;
  const completedGoals = activeMilestones.flatMap(m => m.goals).filter(g => g.done).length;
  const progressPercent = totalGoals > 0 ? Math.round((completedGoals / totalGoals) * 100) : 0;

  if (loading && !data) return <DashboardSkeleton />;

  const knownSkillsList = knownSkillsInput.split(',').map(s => s.trim()).filter(Boolean);
  const targetGapSkillsList = learningGoalsInput.split(',').map(s => s.trim()).filter(Boolean);

  const radarData = data?.skillBreakdown?.slice(0, 8).map(s => ({
    name: s.label?.substring(0, 14) || 'Skill',
    score: s.currentScore || 0,
    required: 70,
  })) || [
    { name: 'React', score: 85, required: 70 },
    { name: 'Node.js', score: 78, required: 70 },
    { name: 'DSA', score: 92, required: 80 },
    { name: 'MongoDB', score: 74, required: 70 },
    { name: 'System Design', score: 60, required: 75 },
  ];

  return (
    <PageTransition className="space-y-6">
      {/* Header */}
      <StaggerItem className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold mb-1">🎯 AI Career Path & Study Guidance Generator</h1>
          <p className="text-gray-500 font-medium">Input your current known skills, target role, and gap goals to generate a personalized learning roadmap</p>
        </div>
      </StaggerItem>

      {/* Career Path Input Form Card */}
      <StaggerItem>
        <NeuCard className="p-6 bg-white space-y-4 border-[3px] border-[var(--ink)] shadow-[4px_4px_0px_#000]">
          <h2 className="text-xl font-bold text-[var(--ink)] flex items-center gap-2">
            ⚙️ Career Path Inputs & Customization
          </h2>

          <div className="grid md:grid-cols-3 gap-4">
            <div>
              <label className="text-xs font-bold text-gray-700 block mb-1">Target Career Role</label>
              <select
                className="neu-select w-full font-bold text-sm bg-white"
                value={selectedRole}
                onChange={e => setSelectedRole(e.target.value)}
              >
                {roles.map(r => (
                  <option key={r.roleId} value={r.roleId}>{r.label}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="text-xs font-bold text-gray-700 block mb-1">Skills You Currently Know</label>
              <input
                type="text"
                className="neu-input w-full text-sm bg-white"
                value={knownSkillsInput}
                onChange={e => setKnownSkillsInput(e.target.value)}
                placeholder="e.g. React, HTML, JS"
              />
            </div>

            <div>
              <label className="text-xs font-bold text-gray-700 block mb-1">Target Skills To Learn / Master</label>
              <input
                type="text"
                className="neu-input w-full text-sm bg-white"
                value={learningGoalsInput}
                onChange={e => setLearningGoalsInput(e.target.value)}
                placeholder="e.g. System Design, Docker, Redis"
              />
            </div>
          </div>

          <div className="pt-2 flex justify-end">
            <NeuButton variant="primary" icon={FiCpu} onClick={handleGenerateAiStudyPlan} loading={generatingPlan}>
              Generate AI Career Path & Roadmap
            </NeuButton>
          </div>
        </NeuCard>
      </StaggerItem>

      {/* Skills Analysis Guidance Summary */}
      <StaggerItem className="grid md:grid-cols-2 gap-4">
        <NeuCard className="p-5 bg-white space-y-3">
          <h3 className="font-bold text-base text-emerald-800 flex items-center gap-2">
            <FiCheckCircle className="text-emerald-600" /> Verified Skills You Know
          </h3>
          <div className="flex flex-wrap gap-2">
            {knownSkillsList.map((sk, idx) => (
              <NeuBadge key={idx} variant="success">
                ✅ {sk}
              </NeuBadge>
            ))}
          </div>
        </NeuCard>

        <NeuCard className="p-5 bg-white space-y-3">
          <h3 className="font-bold text-base text-rose-800 flex items-center gap-2">
            <FiTarget className="text-rose-600" /> Target Skills You Need to Master
          </h3>
          <div className="flex flex-wrap gap-2">
            {targetGapSkillsList.map((sk, idx) => (
              <NeuBadge key={idx} variant="danger">
                🎯 {sk}
              </NeuBadge>
            ))}
          </div>
        </NeuCard>
      </StaggerItem>

      {/* Milestone Progress Cards */}
      <StaggerItem className="grid md:grid-cols-3 gap-4">
        <NeuCard className="p-5 bg-[var(--electric)] text-white text-center">
          <p className="text-xs font-bold uppercase opacity-80 mb-1">Target Role Match</p>
          <p className="text-4xl font-extrabold">{data?.overallReadiness || 78}%</p>
        </NeuCard>

        <NeuCard className="p-5 bg-[var(--mint)] text-center">
          <p className="text-xs font-bold uppercase opacity-80 mb-1">Roadmap Progress</p>
          <p className="text-4xl font-extrabold">{progressPercent}%</p>
        </NeuCard>

        <NeuCard className="p-5 bg-[var(--sky)] text-center">
          <p className="text-xs font-bold uppercase opacity-80 mb-1">Completed Action Items</p>
          <p className="text-4xl font-extrabold">{completedGoals} / {totalGoals}</p>
        </NeuCard>
      </StaggerItem>

      {/* Interactive Milestone Study Roadmap */}
      <StaggerItem>
        <NeuCard className="p-6 bg-white space-y-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b pb-4">
            <div>
              <h2 className="text-xl font-bold flex items-center gap-2">
                🗺️ Active Interactive Milestone Roadmap
              </h2>
              <p className="text-xs text-gray-500 font-medium">
                Tick off completed study goals to update your real-time milestone progress.
              </p>
            </div>
            <div className="w-full sm:w-48 space-y-1">
              <div className="flex justify-between text-xs font-bold">
                <span>Goal Completion</span>
                <span>{progressPercent}%</span>
              </div>
              <div className="w-full h-3 bg-gray-200 rounded-full overflow-hidden border border-[var(--ink)]">
                <div
                  className="h-full bg-[var(--electric)] transition-all duration-300"
                  style={{ width: `${progressPercent}%` }}
                />
              </div>
            </div>
          </div>

          <div className="space-y-4">
            {activeMilestones.map((m, mIdx) => (
              <div key={mIdx} className="p-5 border-[3px] border-[var(--ink)] rounded-2xl bg-[var(--paper)] space-y-3 shadow-[4px_4px_0px_#000]">
                <div className="flex justify-between items-start">
                  <div>
                    <span className="text-xs font-bold text-[var(--electric)] uppercase">Week {m.week} Milestone</span>
                    <h3 className="font-bold text-lg mt-0.5">{m.title}</h3>
                    <p className="text-xs text-gray-600 font-medium">{m.description}</p>
                  </div>
                  <NeuBadge variant={m.completed ? 'success' : 'info'}>
                    {m.completed ? 'Milestone Completed' : 'In Progress'}
                  </NeuBadge>
                </div>

                {/* Interactive Checkboxes List */}
                <div className="space-y-2 pt-2 border-t border-gray-200">
                  <span className="text-xs font-bold text-gray-700 block">Milestone Action Items:</span>
                  {m.goals.map((g) => (
                    <div
                      key={g.id}
                      onClick={() => handleToggleGoal(mIdx, g.id)}
                      className={`p-3 rounded-xl border-2 border-[var(--ink)] flex items-center gap-3 cursor-pointer transition-all ${
                        g.done ? 'bg-emerald-50 text-gray-800 line-through opacity-80' : 'bg-white hover:bg-gray-50'
                      }`}
                    >
                      {g.done ? (
                        <FiCheckSquare className="text-emerald-600 flex-shrink-0" size={20} />
                      ) : (
                        <FiSquare className="text-gray-400 flex-shrink-0" size={20} />
                      )}
                      <span className="text-sm font-semibold">{g.label}</span>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </NeuCard>
      </StaggerItem>

      {/* Skill Gap Radar Chart */}
      <StaggerItem>
        <NeuCard className="p-6 bg-white space-y-4">
          <h2 className="text-xl font-bold flex items-center gap-2">
            📊 Skill Gap Radar Chart ({roles.find(r => r.roleId === selectedRole)?.label || selectedRole})
          </h2>

          <NeuRadarChart
            data={radarData}
            angleKey="name"
            dataKeys={[
              { key: 'score', label: 'Your Verified Score', color: '#4B3AFF' },
              { key: 'required', label: 'Required Target Score', color: '#FF3D9A' },
            ]}
            height={380}
          />
        </NeuCard>
      </StaggerItem>
    </PageTransition>
  );
}
